- name: Install and run nginx
  hosts: web
  become: yes
  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: Run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes